name: Sync assets to CDN
# Triggered every 6 hours on minute 35
on:
  schedule:
    - cron: "35 */12 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    # pogoassets PMSF
    - uses: actions/checkout@v2
      with:
        repository: 'whitewillem/PogoAssets'
        path: 'pogoassets'
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'pogoassets'
        DEST_DIR: 'pogoassets'

    # shuffle PMSF/ICONS
    - uses: actions/checkout@v2
      with:
        repository: 'nileplumb/PkmnShuffleMap'
        path: 'shuffle'
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'shuffle'
        DEST_DIR: 'shuffle'

    # shiny shuffle PMSF
    - uses: actions/checkout@v2
      with:
        repository: 'geekygreek7/pokedave_shuffle_icons_-PMSF-'
        path: 'shinyshuffle'
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'shinyshuffle'
        DEST_DIR: 'shinyshuffle'

    # home PMSF
    - uses: actions/checkout@v2
      with:
        repository: 'nileplumb/PkmnHomeIcons'
        path: 'home'
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'home'
        DEST_DIR: 'home'

    # home ICONS
    - uses: actions/checkout@v2
      with:
        repository: 'nileplumb/PkmnHomeIcons'
        ref: 'ICONS'
        path: 'home_icons'
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'home_icons'
        DEST_DIR: 'home_icons'
