name: Sync assets to CDN
# Triggered every 6 hours on minute 35
on:
  schedule:
    - cron: "35 */12 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: pogoassets checkout (PMSF)
      uses: actions/checkout@v2
      with:
        repository: 'whitewillem/PogoAssets'
        path: 'pogoassets'
    - name: pogoassets sync (PMSF)
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --size-only
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'pogoassets'
        DEST_DIR: 'pogoassets'

    - name: pogoassets checkout (ICONS)
      uses: actions/checkout@v2
      with:
        repository: 'Mygod/pokicons'
        path: 'pogoassets_icons'
    - name: pogoassets sync (ICONS)
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --size-only
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'pogoassets_icons'
        DEST_DIR: 'pogoassets_icons'

    - name: Derpy checkout (PMSF)
      uses: actions/checkout@v2
      with:
        repository: 'tallypokemap/derpysprites'
        path: 'derpy'
    - name: Derpy sync (PMSF)
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --size-only
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'derpy'
        DEST_DIR: 'derpy'

    - name: Awful checkout (PMSF)
      uses: actions/checkout@v2
      with:
        repository: 'ccev/pogoafd'
        path: 'awful'
    - name: Awful sync (PMSF)
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --size-only
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'awful'
        DEST_DIR: 'awful'

    - name: shuffle checkout (PMSF/ICONS)
      uses: actions/checkout@v2
      with:
        repository: 'nileplumb/PkmnShuffleMap'
        path: 'shuffle'
    - name: shuffle sync (PMSF/ICONS)
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --size-only
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'shuffle'
        DEST_DIR: 'shuffle'

    - name: shiny shuffle checkout (PMSF)
      uses: actions/checkout@v2
      with:
        repository: 'geekygreek7/pokedave_shuffle_icons_-PMSF-'
        path: 'shinyshuffle'
    - name: shiny shuffle sync (PMSF)
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --size-only
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'shinyshuffle'
        DEST_DIR: 'shinyshuffle'

    - name: shiny shuffle checkout (ICONS)
      uses: actions/checkout@v2
      with:
        repository: 'Mygod/pokedave_shuffle_icons_-ICONS-'
        path: 'shinyshuffle_icons'
    - name: shiny shuffle sync (ICONS)
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --size-only
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'shinyshuffle_icons'
        DEST_DIR: 'shinyshuffle_icons'

    - name: Home checkout (PMSF)
      uses: actions/checkout@v2
      with:
        repository: 'nileplumb/PkmnHomeIcons'
        path: 'home'
    - name: Home sync (PMSF)
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --size-only
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'home'
        DEST_DIR: 'home'

    - name: Home checkout (ICONS)
      uses: actions/checkout@v2
      with:
        repository: 'nileplumb/PkmnHomeIcons'
        ref: 'ICONS'
        path: 'home_icons'
    - name: Home sync (ICONS)
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks --delete --exclude '.git/*' --size-only
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'home_icons'
        DEST_DIR: 'home_icons'
